name: Grid Search Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r model-backend/requirements.txt

    - name: Run Grid Search
      if: contains(github.event.head_commit.message, 'grid-search-begin')
      run: |
        python model-backend/grid-search.py
        cp voting_classifier.pkl model-backend/
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add model-backend/voting_classifier.pkl
        git commit -m "Add voting classifier model"
        git push origin main
