name: Grid Search Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r model-backend/requirements.txt

    - name: Run Grid Search
      if: contains(github.event.head_commit.message, 'grid-search-begin')
      env:
        GITHUB_TOKEN: ${{ secrets.C_PAT }}
      run: |
        touch test.txt
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add test.txt
        git commit -m "Add voting classifier model"
        git push
    - name: Create Pull Request
      if: contains(github.event.head_commit.message, 'grid-search-begin')
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.C_PAT }}
        title: "Grid Search Changes"
        body: "This pull request was automatically generated by GitHub Actions."
        labels: "automated"
        base: main
        branch: main
