name: Run Specific File and Post Logs

on:
  push:
    branches:
      - main

jobs:
  run_and_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r model-backend/requirements.txt

      - name: Run specific file
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" && "${{ github.event.head_commit.message }}" == *"train-model"* ]]; then
            python model-backend/test.py > logs.txt
            cat logs.txt
            echo "Execution completed."

          else
            echo "Skipping execution as conditions are not met."
          fi
      - name: Create environment file
        run: |
          COMMENT_CONTENT=$(cat logs.txt)
          COMMENT_CONTENT="${COMMENT_CONTENT//'%'/'%25'}"
          COMMENT_CONTENT="${COMMENT_CONTENT//$'\n'/'%0A'}"
          COMMENT_CONTENT="${COMMENT_CONTENT//$'\r'/'%0D'}"
          echo "COMMENT_CONTENT=$COMMENT_CONTENT" >> $GITHUB_ENV
        shell: bash
      - name: Post comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          number: 6
          comment: ${{ env.COMMENT_CONTENT }}
          check-only-first-line: false
          unique: true
          repository: ruchiragahlaut/Low-Resolution
          token: ${{secrets.C_PAT}}  # Reference the repository secret

        env:
            REPO_PAT: ${{secrets.C_PAT}}  # Define the environment variable
      
      