name: Run Specific File and Post Logs

on:
  push:
    branches:
      - main

jobs:
  run_and_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r model-backend/requirements.txt

      - name: Run specific file
        if: contains(github.event.head_commit.message, 'train-model')
        run: |
          python model-backend/test.py > logs.txt
          cat logs.txt
          echo "Execution completed."

      - name: Format comment content
        id: format_content
        if: contains(github.event.head_commit.message, 'train-model')
        run: |
          COMMENT_CONTENT=$(cat logs.txt)
          COMMENT_CONTENT="${COMMENT_CONTENT//'%'/', '}" # Add a comma and two spaces to the end of each line
          COMMENT_CONTENT="${COMMENT_CONTENT//$'\n'/',  '}" # Add a comma and two spaces to the end of each line
          COMMENT_CONTENT="${COMMENT_CONTENT//$'\r'/',  '}" # Add a comma and two spaces to the end of each line
          echo "decoded_content=$COMMENT_CONTENT" >> $GITHUB_ENV

      - name: Post comment
        if: contains(github.event.head_commit.message, 'train-model')
        uses: KeisukeYamashita/create-comment@v1
        with:
          number: 6
          comment: |
            ${{ steps.format_content.outputs.decoded_content }}
          repository: ruchiragahlaut/Low-Resolution
          token: ${{secrets.C_PAT}}  # Reference the repository secret

        env:
            REPO_PAT: ${{secrets.C_PAT}}  # Define the environment variable
      
      # - name: Post comment
      #   uses: KeisukeYamashita/create-comment@v1
      #   with:
      #     number: 6
      #     comment: |
      #       ${{ steps.format_content.outputs.decoded_content }}
      #     repository: ruchiragahlaut/Low-Resolution
      #     token: ${{secrets.C_PAT}}  # Reference the repository secret

      #   env:
      #       REPO_PAT: ${{secrets.C_PAT}}  # Define the environment variable
      
      