name: Run Specific File and Post Logs

on:
  push:
    branches:
      - main

jobs:
  run_and_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r model-backend/requirements.txt

      - name: Run specific file
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" && "${{ github.event.head_commit.message }}" == *"train-model"* ]]; then
            python model-backend/test.py > logs.txt
            cat logs.txt
            echo "Execution completed."

          else
            echo "Skipping execution as conditions are not met."
          fi

      - name: Post logs as comment
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('logs.txt', 'utf8');
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Logs:\n```\n' + content + '\n```'
            });
      - name: Post logs as comment
        if: ${{ success() && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'train-model') }}
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('logs.txt', 'utf8');
            github.issues.createComment({
              issue_number: 6,  # Replace with the actual issue number
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Logs:\n```\n' + content + '\n```'
            });
